### ISSUE TITLE
Problem after update on MacOS

### ISSUE THREAD

**Issue by p-levy** [kcleal/gw#14]
Hello, 
I was able to run an older version of gw but after updating today to the latest (both tried homebrew install and compilation from source), I get the following error: `libc++abi: terminating with uncaught exception of type std::invalid_argument: stoi: no conversion`.
Any idea why and what I should try to fix it? 

Btw this is my Mac / OS look like:
![image](https://user-images.githubusercontent.com/82144282/224331511-fd0e6e6c-a695-4071-a7fa-e421c40c6183.png)

Thanks!
Pierre

**Comment by kcleal** [comment]
Hi @p-levy
Thanks for reporting this. What was your gw command used, and version of gw?

**Comment by p-levy** [comment]
That actually happens with any command. Even `gw --config` or just `gw -h` or `gw`.

**Comment by kcleal** [comment]
Ok that sounds like a problem with an old .gw.ini on your system. You old .gw.ini might be at `~/.gw.ini`, or `~/.config/.gw.ini` or maybe in miniconda bin `~/miniconda/bin/.gw.ini`. If you cant find it, copy from the github page and put it in `~/.gw.ini`, that is the first place gw looks for the ini.

**Comment by p-levy** [comment]
That was it! I replaced the `~/.gw.ini` with the one from github and that worked. :) Thanks!
