### ISSUE TITLE
Load GTF

### ISSUE THREAD

**Issue by Akazhiel** [kcleal/gw#15]
Hello!

Is there a way to load a GTF/GFF file to be able to have a gene/transcript track just like IGV or we have to transform these files into a BED file to load it?

Thanks!

**Comment by kcleal** [comment]
Currently GTF/GFF are not supported. I can add this in the next release though

**Comment by Akazhiel** [comment]
That'd be awesome!

I tried converting a gtf into a bed and successfully load it but there's the issue that everything that overlaps is collapsed in the same track instead of being expanded like you can do in IGV.

**Comment by kcleal** [comment]
I can see that would be annoying. I need to do a bit more work on overlapping features. Igv has some nice ways to collapse and expand features, I think this should also be supported in gw.

**Comment by kcleal** [comment]
GTF/GFF3 is now supported in v0.9, along with expandable tracks!
