### ISSUE TITLE
`Error: Null iterator when trying to fetch from HTS file in collectReadsAndCoverage`

### ISSUE THREAD

**Issue by jashephe** [kcleal/gw#16]
On fresh install of `gw` on macOS 13.4.1, I'm just trying to visualize a single BAM file with:

```
gw hg38 -b mybam.bam
```

GW launches with a blank window. When I try running `:goto chr1 1:10000`, `gw` crashes, with the following output:

```
Error: Null iterator when trying to fetch from HTS file in collectReadsAndCoverage chr1 1 10000
libc++abi: terminating
fish: Job 1, 'gw hg38 -b mybam.bam' terminated by signal SIGABRT (Abort)
```

The BAM file was sorted and indexed with `samtools` and the index is located in the same directory as the BAM file (`mybam.bam.bai`). I have no issues loading the sam BAM file into IGV.

**Comment by kcleal** [comment]
Hi @jashephe, that is a bit unexpected. Its possible the hg38 or bam file have different chromosome naming conventions i.e. one is using `chr1` and the other is using `1`. I had a look over the code and the `:goto` command does not currently check for this and raise an error, so it could well be the case! The online hg38 that `gw` has listed in the `.gw.ini` file has the `chr1` convention - there is no automatic conversion currently.

Btw, if you are navigating to a single region, you can just type type `:chr1` which will take you to the start of the chromosome, or `:chr1:1-20000` etc (goto is not needed for a single region)

**Comment by jashephe** [comment]
Hi @kcleal. Thanks for the suggestions, I actually get the same error when using the reference genome the BAM files were aligned against, rather than the online hg38; e.g. launching `gw` with:

```
gw mygenome.fa -b mybam.bai
```

and then running the same `:goto` command, or using `:chr1`.

Not sure if it is relevant, but I am on an Apple Silicon (M1) mac.

If you have a "known good" BAM file you could point me towards that is known to work with the online `hg38` reference, I'd be happy to download it and try it. Alternatively, I'd be happy to share a link to the BAM file I am using.

**Comment by kcleal** [comment]
Ok, strange. 

There is a test.bam and a test.fa in the test folder if you want to try those. 

I have tested gw on M1 before, so it should work. If you could send me a small bit of your bam file, I can also have a quick go - email to clealk@cardiff.ac.uk.

**Comment by jashephe** [comment]
Just wanted to follow up on this; I was able to open the `test.bam` and `test.fa` files, so looks like there's something weird about my files. I don't have the time to invest in following up, so I'll go ahead and close this issue. Cheers!
