### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by warthmann** [kcleal/gw#18]
Hello, I am new to gw and a first time user.

**Describe the bug**
```
sudo apt install libgl1-mesa-dev
sudo apt install libfontconfig-dev
sudo apt install libhts-dev
sudo apt install glfw
mamba install -c conda-forge -c bioconda gw
```

`gw /home/norman/genome.fa` gives a segmentation fault. genome.fa is a multi-fasta file containing the Brachypodium genome and /home/norman/genome.fa.fai is the index.

same segmentation fault with
`gw hg38`

![Screenshot from 2023-11-30 13-59-52](https://github.com/kcleal/gw/assets/9294152/969a5dd7-6493-4508-981d-4f12a6800524)

**System (please complete the following information):**
 - GW version 0.8.2
 - OS: Ubuntu Linux 20.04

**Comment by kcleal** [comment]
Hi @warthmann,
Thanks for trying gw, apologies for the error. 

You may need to supply the bam and region arguments. I think there are some bugs in v0.8.2, these should be resolved in the up-coming release. Your command should look something like:

`gw ref.fa -b a.bam -r chr1`

Alternatively, sometimes apt installing glfw3 fetches an old version. Version >= 3.3.8 glfw3 might be needed.

**Comment by warthmann** [comment]
thank you. It is working now. Not sure what  ended up being the cause, but I made sure I had the correct NVIDIA driver, updated all packages, installed libglfw3 and libglfw3-dev, and rebooted the machine.
