### ISSUE TITLE
error when installing GW

### ISSUE THREAD

**Issue by sujunhao** [kcleal/gw#2]
hi,

I tried to follow the instruction to install GW in my environment, but it failed with the following error:
```
$ make
gcc -g -Wall -std=c++17  -fno-common -dynamic -fwrapv -O3 -DNDEBUG -D LINUX -g -I./include -I./src -I. -I./gw -I/usr/local/include -I./lib/skia -c src/themes.cpp -o src/themes.o
cc1plus: warning: unrecognized gcc debugging option: y
cc1plus: warning: unrecognized gcc debugging option: n
cc1plus: warning: unrecognized gcc debugging option: m
cc1plus: warning: unrecognized gcc debugging option: i
cc1plus: warning: unrecognized gcc debugging option: c
In file included from src/themes.cpp:4:0:
src/themes.h:7:24: fatal error: GLFW/glfw3.h: No such file or directory
compilation terminated.
Makefile:86: recipe for target 'src/themes.o' failed
make: *** [src/themes.o] Error 1
```
Do you have any hints to solve the problem?  Thanks.

**Comment by kcleal** [comment]
Hi @sujunhao ,
You will need to install glfw3 separately https://www.glfw.org/download (usually with root permissions). I am trying to get gw onto conda at the moment which should resolve this issue, if you dont mind waiting

**Comment by sujunhao** [comment]
Hi @kcleal,
A conda installation option will be more appropriate for me, as I don't have root privilege. I will try to reinstall the tool when the conda version is ready. 
Thanks.

**Comment by kcleal** [comment]
GW is now available on the bioconda channel 🙂

**Comment by sujunhao** [comment]
thanks @kcleal,

GW is well-functional in my environment now,
![image](https://user-images.githubusercontent.com/10023931/201038515-bf1073b3-9d3e-424b-9f50-9004ff8537a3.png)
