### ISSUE TITLE
error when used on remote server (libGL)

### ISSUE THREAD

**Issue by pcantalupo** [kcleal/gw#3]
Hello,  I created a conda environment for gw. 

```
$ cat ~/.condarc 
channels:
  - conda-forge
  - bioconda
  - defaults
$ conda create --name gwbrowser gw
```

When I tried indexing my genome, I got this error and not sure how to fix it.

```
(gwbrowser) $ gw GRCh38.primary_assembly_withBKV.fa 

█▀▀ █ █ █
█▄█ ▀▄▀▄▀
ERROR: could not initialize GLFW3
terminate called without an active exception
Aborted (core dumped)
```

**Comment by kcleal** [comment]
Hi @pcantalupo,

What system are you using? It looks like conda did not install glfw3 properly, or maybe did not set the env variables properly. Can you check for glfw3 in the conda lib? It should be under something like `/home/kez/miniconda3/envs/gw_env/lib/libglfw.so`

If glfw3 is installed, the you can try setting the LD_LIBRARY_PATH to include that folder

**Comment by pcantalupo** [comment]
My local desktop is an iMac (Retina 5K 27 inch display) and I ssh into the linux cluster.

```
$ uname -a
Linux 3.10.0-1062.4.1.el7.x86_64 #1 SMP Wed Sep 25 09:42:57 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kcleal** [comment]
Ok, it might be an issue with X11 forwarding. Did you login with `ssh -v -X` ? Also you can try `ssh -v -Y user@cluster`

**Comment by pcantalupo** [comment]
`ssh -v -X` gave same error but `ssh -v -Y` gave me this:

```
$ gw GRCh38.primary_assembly_withBKV.fa 

█▀▀ █ █ █
█▄█ ▀▄▀▄▀
debug1: client_input_channel_open: ctype x11 rchan 2 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 51394
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 1: new [x11]
debug1: confirm x11
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  142
  Current serial number in output stream:  142
debug1: channel 1: FORCE input drain
debug1: channel 1: free: x11, nchannels 2
```

It created the *fai file as it did before.  Then I tried viewing a bam file but got what looks like a similar error:

```
$ gw GRCh38.primary_assembly_withBKV.fa -b ~/projects/star_salmon/R-B-11hr.markdup.sorted.bam 

█▀▀ █ █ █
█▄█ ▀▄▀▄▀
debug1: client_input_channel_open: ctype x11 rchan 2 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 51432
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 1: new [x11]
debug1: confirm x11
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  142
  Current serial number in output stream:  142
debug1: channel 1: FORCE input drain
debug1: channel 1: free: x11, nchannels 2
```

**Comment by kcleal** [comment]
It looks like this is your problem:

    libGL error: No matching fbConfigs or visuals found
    libGL error: failed to load driver: swrast

These are opengl libraries that are missing. This will probably be hard to fix without root permissions. Do you have a sys admin to contact about this?

**Comment by pcantalupo** [comment]
Ok, I'll follow up with the sys admin...thank you
