### ISSUE TITLE
Visualize multiple read groups from one bam

### ISSUE THREAD

**Issue by chklopp** [kcleal/gw#4]
Multi_windows view is a really nice feature. Would it be possible to show different bam files or read groups from the same bam in order to visually check variants?

**Comment by kcleal** [comment]
Hi @chklopp,
I think that would be a nice feature. How about it the read group could be accessed from the filter command, so you could filter for reads with the same read group, for example? Is this what you had in mind?

**Comment by chklopp** [comment]
Biologists with whom we work often manually check long variants using IGV. They load multiple bams and visualize the alignments. But the IGV screen is limited and they have to scroll or open multiple IGVs.
Filtering multiple read groups for one location would enable gw to present each read group alignment in a separate window. Or perhaps have a parameter such as --use-rg. If it is set, gw would show alignments by read groups.

**Comment by kcleal** [comment]
Im still a little confused, sounds a bit more like a group-by operation? Let me see if Ive understood you correctly. Firstly do you mean read groups as in https://gatk.broadinstitute.org/hc/en-us/articles/360035890671-Read-groups e.g.
  
    @RG ID:H0164.2  PL:illumina PU:H0164ALXX140820.2    LB:Solexa-272222    PI:0    DT:2014-08-20T00:00:00-0400 SM:NA12878  CN:BI

Say you have a few different regions open, so your screen looks a bit like

  ---------------------------------------------
 |  region 1                   |   region 2                     |
 |  chr1:1-20000          |   chr1:70000-80000   |
 ---------------------------------------------

Would you would like region 1 to show one read group identifier, and region 2 a different identifier? 
Or do you mean, say you have more than one bam open, screen looks like:

  ---------------------------------------------
 |  region 1 bam1          |   region 2 bam1           |
 |  chr1:1-20000          |   chr1:70000-80000   |
 ---------------------------------------------
 |  region 1 bam2         |   region 2 bam2           |
 |  chr1:1-20000          |   chr1:70000-80000   |
 ---------------------------------------------

Do you want bam1 to show one read group identifier, and bam2 a different identifier (horizontal plane of region1, bam1 and region2 bam2 has the same read group)?

I guess it would also be possible to have each pane have a separate filtering command issued, so all four panes could be filtered differently.

**Comment by chklopp** [comment]
1/ read group as in @RG (in the bam file).
2/ the second solution fits : same region but different @RG or bam in different panels. To compare @RG in the same region a column display layout would be best.

**Comment by kcleal** [comment]
Ok I think I understand. I had in mind extending the ``:filter`` command syntax to also include array indexing - this would make filtering a bit more flexible (but the syntax a bit more ugly). So you could use something like `:filter rg-SM == sample1 [:, 0]`  the ``:`` would select all rows, and ``0`` would select first column.

**Comment by chklopp** [comment]
Splitting read groups is really fine, but in many cases our users will have separate bams (and merging them would be tedious when genomes are large) and I did not understand from the documentation if it was already possible to input several bams and show them in different windows for the same locations.

**Comment by kcleal** [comment]
It is already possible to display multiple bams. Each bam takes up its own row and regions are columns. You can use the -b option multiple times, or drag and drop a new bam. I will try and get this merged today

**Comment by chklopp** [comment]
Thank you for this clarification.
