### ISSUE TITLE
Sort alignments by Base

### ISSUE THREAD

**Issue by ifdongs** [kcleal/gw#44]
Hi,
Very powerful tool
When I use igv, I often need to cluster the same bases together for display. Are there any relevant settings that can achieve similar functions?
Thanks

![image](https://github.com/user-attachments/assets/e8201ba1-ab84-42c2-a3fc-5345d842cc07)
![image](https://github.com/user-attachments/assets/efa1fb43-fd18-47e7-a933-6b6ac0eb4030)

**Comment by kcleal** [comment]
Hi @ifdongs,
Thanks for the suggestion. I think it could be done, but will need some more details.
Could you describe what you mean a bit more clearly, or what function in IGV you want to replicate - It sounds like you want all of the reads with the T variant at the top of the screen, and all other reads below that? In IGV you can right-click then select Group by -> base at position X. Is that what you mean?

**Comment by ifdongs** [comment]
@kcleal ,  Yes, 
the specific operational details: `right-click`  --  `Sort alignment by`  --  `base`
or use hot-keys:  `ctrl+s`

In some plasma sequencing, the sequencing depth is more than 5000×, and the mutation signal intensity is very low, often less than 0.5%, the mutations will be randomly distributed in the GW screenshot and difficult to identify.
If the mutant reads at the top of the screen,  gw snipshots will have a better display effect.

i have only used it on linux without x11 before. Can kmer be achieved by setting gw.ini?

Thanks

**Comment by ifdongs** [comment]
exciting 👍 👍 
Thanks

**Comment by kcleal** [comment]
Hi @ifdongs,
I have added this in v1.1.0. You will need to clone the repo and build from source if you would like to test before the release is finalized. The full release will take a bit longer to prepare. 
Reads can be sorted using the 'S' hot key (mouse over the target base), or you can use a command `sort 120000` or `sort strand 120000`, for example. Sorting can also be applied from the CLI using the new `--command` or `-c` option. For example `--command 'sort 12000'` can be used.

**Comment by kcleal** [comment]
v1.1.0 is now available
