### ISSUE TITLE
GW window all black

### ISSUE THREAD

**Issue by p-levy** [kcleal/gw#5]
Hi, thanks for developing this great tool! 
I'm having an issue when trying to run gw. The simple command `gw GRCh38.primary_assembly.genome.fa` opens a GW window that stays all black. I also tried loading a bam file but it didn't help. 
I installed gw via conda in a new environment. I'm working on Mac OS. 
Any idea what could be the problem? I don't get any error message.

**Comment by kcleal** [comment]
Possibly you just need to specify a region. Try adding one with ``:goto chr1:1-20000`` as a command (make sure to click on the gw window first), or from the command line ``-r chr1:1-20000``

**Comment by p-levy** [comment]
Sorry I forgot to mention that I also tried that and it doesn't help. 

<img width="2047" alt="Screenshot 2022-11-17 at 11 55 14" src="https://user-images.githubusercontent.com/82144282/202428096-4c505595-79a8-47b8-bae2-aa1a644bf030.png">

<img width="880" alt="Screenshot 2022-11-17 at 11 53 14" src="https://user-images.githubusercontent.com/82144282/202428101-f7a95930-30a9-4fc8-90bd-d79e3396534a.png">

For some reason when I try now specifying the region it returns a `Segmentation fault: 11`.

**Comment by kcleal** [comment]
Does it work if you specify a bam file on the command line?

    gw GRCh38 -r chr1:1-20000 -b your.bam

Im actually in the process of fixing a few bugs related to opening regions without a bam file, so I might have already addressed this. I will try and commit the changes within the hour.

**Comment by p-levy** [comment]
Unfortunately it looks the same when I specify a bam file from the command line.

**Comment by p-levy** [comment]
I downgraded to version `0.1.7` and it looks the same

**Comment by kcleal** [comment]
Ok, that is a bit confusing. Would you mind sending me a small sample of that bam file clealk@cardiff.ac.uk? You can use ``samtools view -bh your.bam chr1:1-20000 > test.bam``. Im not sure of the problem at the moment, sorry.

**Comment by kcleal** [comment]
Thanks for the bam file. Weirdly, I have no problems viewing it. It could be something to do with your graphics drivers - what system are you using? If you are using an old Mac this might cause some problems. Also you might be better off trying to build gw from source, although you will need to install glfw and htslib beforehand

**Comment by p-levy** [comment]
A little old, but still working pretty good for most applications!

<img width="247" alt="Screenshot 2022-11-17 at 12 36 41" src="https://user-images.githubusercontent.com/82144282/202436238-93dce121-6506-41ab-abb8-4a9042ef3b26.png">

I'll try building from source. Thanks!

**Comment by kcleal** [comment]
I have tested gw on a 2014 mac so it should work on yours. Hopefully building from source will do it - let me know

**Comment by p-levy** [comment]
It worked after building from source! :)

**Comment by kcleal** [comment]
Great!
