### ISSUE TITLE
Dockerized container

### ISSUE THREAD

**Issue by husamia** [kcleal/gw#8]
I am having issues compiling gw and other dependencies issues. I tried conda install, it was giving me some other errors. Can you create a dockerized container to run gw without having to compile or install it with conda?

**Comment by kcleal** [comment]
Hi @husamia,
I have been working on a docker for GW, but unfortunately it's actually very hard to get an opengl interface working between the host and container.
For now, your best bet it to get conda/local build working. I can try and help you get up and running if you provide some more info:
-what have you tried and what was the error?
-what system are you using?
-what is the compiler g++/clang++? What is the compiler version?

**Comment by husamia** [comment]
I am compiling it from source inside a docker container. I get the error 

src/themes.h:7:24: fatal error: GLFW/glfw3.h: No such file or directory
 #include <GLFW/glfw3.h>
                        ^
compilation terminated.
Makefile:90: recipe for target 'src/themes.o' failed
make: *** [src/themes.o] Error 1

so if I cant used it inside a container I may not be able to run it. Thanks

**Comment by kcleal** [comment]
If building from source you will need to install glfw and htslib.
If you have conda, you can use

    mamba install glfw htslib
    export CONDA_PREFIX=/pathTo/miniconda
    git clone https://github.com/kcleal/gw.git && cd gw
    make

However, this probably still wont work using docker as the container needs to be configured to support a window interface between the host and container - this is not something I have managed to set up correctly before, but you may have more luck. 
What was the issue building on your outside a docker container? I expect this will be easier to solve

**Comment by husamia** [comment]
I didn't try outside docker.

**Comment by kcleal** [comment]
A docker conatiner for gw is now available. `docker pull kcleal/gw`.
Instructions for how to use the container are here: https://hub.docker.com/repository/docker/kcleal/gw
